// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: url_service.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Shortener_CreateURL_FullMethodName        = "/Shortener/CreateURL"
	Shortener_GetURL_FullMethodName           = "/Shortener/GetURL"
	Shortener_GetStats_FullMethodName         = "/Shortener/GetStats"
	Shortener_UpdateURL_FullMethodName        = "/Shortener/UpdateURL"
	Shortener_DeleteURL_FullMethodName        = "/Shortener/DeleteURL"
	Shortener_ListURLs_FullMethodName         = "/Shortener/ListURLs"
	Shortener_GetQRCode_FullMethodName        = "/Shortener/GetQRCode"
	Shortener_GetVisitSummary_FullMethodName  = "/Shortener/GetVisitSummary"
	Shortener_GetVisitsByDate_FullMethodName  = "/Shortener/GetVisitsByDate"
	Shortener_GetVisitsByField_FullMethodName = "/Shortener/GetVisitsByField"
	Shortener_GetRecentVisits_FullMethodName  = "/Shortener/GetRecentVisits"
	Shortener_GetOrphanVisits_FullMethodName  = "/Shortener/GetOrphanVisits"
	Shortener_ListTags_FullMethodName         = "/Shortener/ListTags"
	Shortener_CreateTag_FullMethodName        = "/Shortener/CreateTag"
	Shortener_RenameTag_FullMethodName        = "/Shortener/RenameTag"
	Shortener_DeleteTag_FullMethodName        = "/Shortener/DeleteTag"
	Shortener_GetTagStats_FullMethodName      = "/Shortener/GetTagStats"
	Shortener_PreviewURL_FullMethodName       = "/Shortener/PreviewURL"
)

// ShortenerClient is the client API for Shortener service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ShortenerClient interface {
	CreateURL(ctx context.Context, in *CreateURLRequest, opts ...grpc.CallOption) (*ShortURL, error)
	GetURL(ctx context.Context, in *GetURLRequest, opts ...grpc.CallOption) (*ShortURL, error)
	GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*StatsResponse, error)
	UpdateURL(ctx context.Context, in *UpdateURLRequest, opts ...grpc.CallOption) (*ShortURL, error)
	DeleteURL(ctx context.Context, in *DeleteURLRequest, opts ...grpc.CallOption) (*DeleteURLResponse, error)
	ListURLs(ctx context.Context, in *ListURLsRequest, opts ...grpc.CallOption) (*ListURLsResponse, error)
	GetQRCode(ctx context.Context, in *GetQRCodeRequest, opts ...grpc.CallOption) (*QRCodeResponse, error)
	GetVisitSummary(ctx context.Context, in *GetVisitSummaryRequest, opts ...grpc.CallOption) (*VisitSummaryResponse, error)
	GetVisitsByDate(ctx context.Context, in *GetVisitsByDateRequest, opts ...grpc.CallOption) (*VisitsByDateResponse, error)
	GetVisitsByField(ctx context.Context, in *GetVisitsByFieldRequest, opts ...grpc.CallOption) (*VisitsByFieldResponse, error)
	GetRecentVisits(ctx context.Context, in *GetRecentVisitsRequest, opts ...grpc.CallOption) (*RecentVisitsResponse, error)
	GetOrphanVisits(ctx context.Context, in *GetOrphanVisitsRequest, opts ...grpc.CallOption) (*OrphanVisitsResponse, error)
	// Tag management
	ListTags(ctx context.Context, in *ListTagsRequest, opts ...grpc.CallOption) (*ListTagsResponse, error)
	CreateTag(ctx context.Context, in *CreateTagRequest, opts ...grpc.CallOption) (*TagInfo, error)
	RenameTag(ctx context.Context, in *RenameTagRequest, opts ...grpc.CallOption) (*TagInfo, error)
	DeleteTag(ctx context.Context, in *DeleteTagRequest, opts ...grpc.CallOption) (*DeleteTagResponse, error)
	GetTagStats(ctx context.Context, in *GetTagStatsRequest, opts ...grpc.CallOption) (*TagStatsResponse, error)
	// Public link preview (no auth required) — like bit.ly's code+ feature
	PreviewURL(ctx context.Context, in *PreviewURLRequest, opts ...grpc.CallOption) (*PreviewURLResponse, error)
}

type shortenerClient struct {
	cc grpc.ClientConnInterface
}

func NewShortenerClient(cc grpc.ClientConnInterface) ShortenerClient {
	return &shortenerClient{cc}
}

func (c *shortenerClient) CreateURL(ctx context.Context, in *CreateURLRequest, opts ...grpc.CallOption) (*ShortURL, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShortURL)
	err := c.cc.Invoke(ctx, Shortener_CreateURL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shortenerClient) GetURL(ctx context.Context, in *GetURLRequest, opts ...grpc.CallOption) (*ShortURL, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShortURL)
	err := c.cc.Invoke(ctx, Shortener_GetURL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shortenerClient) GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*StatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatsResponse)
	err := c.cc.Invoke(ctx, Shortener_GetStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shortenerClient) UpdateURL(ctx context.Context, in *UpdateURLRequest, opts ...grpc.CallOption) (*ShortURL, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShortURL)
	err := c.cc.Invoke(ctx, Shortener_UpdateURL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shortenerClient) DeleteURL(ctx context.Context, in *DeleteURLRequest, opts ...grpc.CallOption) (*DeleteURLResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteURLResponse)
	err := c.cc.Invoke(ctx, Shortener_DeleteURL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shortenerClient) ListURLs(ctx context.Context, in *ListURLsRequest, opts ...grpc.CallOption) (*ListURLsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListURLsResponse)
	err := c.cc.Invoke(ctx, Shortener_ListURLs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shortenerClient) GetQRCode(ctx context.Context, in *GetQRCodeRequest, opts ...grpc.CallOption) (*QRCodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QRCodeResponse)
	err := c.cc.Invoke(ctx, Shortener_GetQRCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shortenerClient) GetVisitSummary(ctx context.Context, in *GetVisitSummaryRequest, opts ...grpc.CallOption) (*VisitSummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VisitSummaryResponse)
	err := c.cc.Invoke(ctx, Shortener_GetVisitSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shortenerClient) GetVisitsByDate(ctx context.Context, in *GetVisitsByDateRequest, opts ...grpc.CallOption) (*VisitsByDateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VisitsByDateResponse)
	err := c.cc.Invoke(ctx, Shortener_GetVisitsByDate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shortenerClient) GetVisitsByField(ctx context.Context, in *GetVisitsByFieldRequest, opts ...grpc.CallOption) (*VisitsByFieldResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VisitsByFieldResponse)
	err := c.cc.Invoke(ctx, Shortener_GetVisitsByField_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shortenerClient) GetRecentVisits(ctx context.Context, in *GetRecentVisitsRequest, opts ...grpc.CallOption) (*RecentVisitsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecentVisitsResponse)
	err := c.cc.Invoke(ctx, Shortener_GetRecentVisits_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shortenerClient) GetOrphanVisits(ctx context.Context, in *GetOrphanVisitsRequest, opts ...grpc.CallOption) (*OrphanVisitsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrphanVisitsResponse)
	err := c.cc.Invoke(ctx, Shortener_GetOrphanVisits_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shortenerClient) ListTags(ctx context.Context, in *ListTagsRequest, opts ...grpc.CallOption) (*ListTagsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTagsResponse)
	err := c.cc.Invoke(ctx, Shortener_ListTags_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shortenerClient) CreateTag(ctx context.Context, in *CreateTagRequest, opts ...grpc.CallOption) (*TagInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TagInfo)
	err := c.cc.Invoke(ctx, Shortener_CreateTag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shortenerClient) RenameTag(ctx context.Context, in *RenameTagRequest, opts ...grpc.CallOption) (*TagInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TagInfo)
	err := c.cc.Invoke(ctx, Shortener_RenameTag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shortenerClient) DeleteTag(ctx context.Context, in *DeleteTagRequest, opts ...grpc.CallOption) (*DeleteTagResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteTagResponse)
	err := c.cc.Invoke(ctx, Shortener_DeleteTag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shortenerClient) GetTagStats(ctx context.Context, in *GetTagStatsRequest, opts ...grpc.CallOption) (*TagStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TagStatsResponse)
	err := c.cc.Invoke(ctx, Shortener_GetTagStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shortenerClient) PreviewURL(ctx context.Context, in *PreviewURLRequest, opts ...grpc.CallOption) (*PreviewURLResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PreviewURLResponse)
	err := c.cc.Invoke(ctx, Shortener_PreviewURL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShortenerServer is the server API for Shortener service.
// All implementations must embed UnimplementedShortenerServer
// for forward compatibility.
type ShortenerServer interface {
	CreateURL(context.Context, *CreateURLRequest) (*ShortURL, error)
	GetURL(context.Context, *GetURLRequest) (*ShortURL, error)
	GetStats(context.Context, *GetStatsRequest) (*StatsResponse, error)
	UpdateURL(context.Context, *UpdateURLRequest) (*ShortURL, error)
	DeleteURL(context.Context, *DeleteURLRequest) (*DeleteURLResponse, error)
	ListURLs(context.Context, *ListURLsRequest) (*ListURLsResponse, error)
	GetQRCode(context.Context, *GetQRCodeRequest) (*QRCodeResponse, error)
	GetVisitSummary(context.Context, *GetVisitSummaryRequest) (*VisitSummaryResponse, error)
	GetVisitsByDate(context.Context, *GetVisitsByDateRequest) (*VisitsByDateResponse, error)
	GetVisitsByField(context.Context, *GetVisitsByFieldRequest) (*VisitsByFieldResponse, error)
	GetRecentVisits(context.Context, *GetRecentVisitsRequest) (*RecentVisitsResponse, error)
	GetOrphanVisits(context.Context, *GetOrphanVisitsRequest) (*OrphanVisitsResponse, error)
	// Tag management
	ListTags(context.Context, *ListTagsRequest) (*ListTagsResponse, error)
	CreateTag(context.Context, *CreateTagRequest) (*TagInfo, error)
	RenameTag(context.Context, *RenameTagRequest) (*TagInfo, error)
	DeleteTag(context.Context, *DeleteTagRequest) (*DeleteTagResponse, error)
	GetTagStats(context.Context, *GetTagStatsRequest) (*TagStatsResponse, error)
	// Public link preview (no auth required) — like bit.ly's code+ feature
	PreviewURL(context.Context, *PreviewURLRequest) (*PreviewURLResponse, error)
	mustEmbedUnimplementedShortenerServer()
}

// UnimplementedShortenerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedShortenerServer struct{}

func (UnimplementedShortenerServer) CreateURL(context.Context, *CreateURLRequest) (*ShortURL, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateURL not implemented")
}
func (UnimplementedShortenerServer) GetURL(context.Context, *GetURLRequest) (*ShortURL, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetURL not implemented")
}
func (UnimplementedShortenerServer) GetStats(context.Context, *GetStatsRequest) (*StatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStats not implemented")
}
func (UnimplementedShortenerServer) UpdateURL(context.Context, *UpdateURLRequest) (*ShortURL, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateURL not implemented")
}
func (UnimplementedShortenerServer) DeleteURL(context.Context, *DeleteURLRequest) (*DeleteURLResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteURL not implemented")
}
func (UnimplementedShortenerServer) ListURLs(context.Context, *ListURLsRequest) (*ListURLsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListURLs not implemented")
}
func (UnimplementedShortenerServer) GetQRCode(context.Context, *GetQRCodeRequest) (*QRCodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetQRCode not implemented")
}
func (UnimplementedShortenerServer) GetVisitSummary(context.Context, *GetVisitSummaryRequest) (*VisitSummaryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVisitSummary not implemented")
}
func (UnimplementedShortenerServer) GetVisitsByDate(context.Context, *GetVisitsByDateRequest) (*VisitsByDateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVisitsByDate not implemented")
}
func (UnimplementedShortenerServer) GetVisitsByField(context.Context, *GetVisitsByFieldRequest) (*VisitsByFieldResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVisitsByField not implemented")
}
func (UnimplementedShortenerServer) GetRecentVisits(context.Context, *GetRecentVisitsRequest) (*RecentVisitsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRecentVisits not implemented")
}
func (UnimplementedShortenerServer) GetOrphanVisits(context.Context, *GetOrphanVisitsRequest) (*OrphanVisitsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrphanVisits not implemented")
}
func (UnimplementedShortenerServer) ListTags(context.Context, *ListTagsRequest) (*ListTagsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTags not implemented")
}
func (UnimplementedShortenerServer) CreateTag(context.Context, *CreateTagRequest) (*TagInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTag not implemented")
}
func (UnimplementedShortenerServer) RenameTag(context.Context, *RenameTagRequest) (*TagInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RenameTag not implemented")
}
func (UnimplementedShortenerServer) DeleteTag(context.Context, *DeleteTagRequest) (*DeleteTagResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTag not implemented")
}
func (UnimplementedShortenerServer) GetTagStats(context.Context, *GetTagStatsRequest) (*TagStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTagStats not implemented")
}
func (UnimplementedShortenerServer) PreviewURL(context.Context, *PreviewURLRequest) (*PreviewURLResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PreviewURL not implemented")
}
func (UnimplementedShortenerServer) mustEmbedUnimplementedShortenerServer() {}
func (UnimplementedShortenerServer) testEmbeddedByValue()                   {}

// UnsafeShortenerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShortenerServer will
// result in compilation errors.
type UnsafeShortenerServer interface {
	mustEmbedUnimplementedShortenerServer()
}

func RegisterShortenerServer(s grpc.ServiceRegistrar, srv ShortenerServer) {
	// If the following call pancis, it indicates UnimplementedShortenerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Shortener_ServiceDesc, srv)
}

func _Shortener_CreateURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateURLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShortenerServer).CreateURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Shortener_CreateURL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShortenerServer).CreateURL(ctx, req.(*CreateURLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Shortener_GetURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetURLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShortenerServer).GetURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Shortener_GetURL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShortenerServer).GetURL(ctx, req.(*GetURLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Shortener_GetStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShortenerServer).GetStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Shortener_GetStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShortenerServer).GetStats(ctx, req.(*GetStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Shortener_UpdateURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateURLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShortenerServer).UpdateURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Shortener_UpdateURL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShortenerServer).UpdateURL(ctx, req.(*UpdateURLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Shortener_DeleteURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteURLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShortenerServer).DeleteURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Shortener_DeleteURL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShortenerServer).DeleteURL(ctx, req.(*DeleteURLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Shortener_ListURLs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListURLsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShortenerServer).ListURLs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Shortener_ListURLs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShortenerServer).ListURLs(ctx, req.(*ListURLsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Shortener_GetQRCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetQRCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShortenerServer).GetQRCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Shortener_GetQRCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShortenerServer).GetQRCode(ctx, req.(*GetQRCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Shortener_GetVisitSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVisitSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShortenerServer).GetVisitSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Shortener_GetVisitSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShortenerServer).GetVisitSummary(ctx, req.(*GetVisitSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Shortener_GetVisitsByDate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVisitsByDateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShortenerServer).GetVisitsByDate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Shortener_GetVisitsByDate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShortenerServer).GetVisitsByDate(ctx, req.(*GetVisitsByDateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Shortener_GetVisitsByField_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVisitsByFieldRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShortenerServer).GetVisitsByField(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Shortener_GetVisitsByField_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShortenerServer).GetVisitsByField(ctx, req.(*GetVisitsByFieldRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Shortener_GetRecentVisits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRecentVisitsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShortenerServer).GetRecentVisits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Shortener_GetRecentVisits_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShortenerServer).GetRecentVisits(ctx, req.(*GetRecentVisitsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Shortener_GetOrphanVisits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrphanVisitsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShortenerServer).GetOrphanVisits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Shortener_GetOrphanVisits_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShortenerServer).GetOrphanVisits(ctx, req.(*GetOrphanVisitsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Shortener_ListTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTagsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShortenerServer).ListTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Shortener_ListTags_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShortenerServer).ListTags(ctx, req.(*ListTagsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Shortener_CreateTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShortenerServer).CreateTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Shortener_CreateTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShortenerServer).CreateTag(ctx, req.(*CreateTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Shortener_RenameTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenameTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShortenerServer).RenameTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Shortener_RenameTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShortenerServer).RenameTag(ctx, req.(*RenameTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Shortener_DeleteTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShortenerServer).DeleteTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Shortener_DeleteTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShortenerServer).DeleteTag(ctx, req.(*DeleteTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Shortener_GetTagStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTagStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShortenerServer).GetTagStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Shortener_GetTagStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShortenerServer).GetTagStats(ctx, req.(*GetTagStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Shortener_PreviewURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PreviewURLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShortenerServer).PreviewURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Shortener_PreviewURL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShortenerServer).PreviewURL(ctx, req.(*PreviewURLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Shortener_ServiceDesc is the grpc.ServiceDesc for Shortener service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Shortener_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Shortener",
	HandlerType: (*ShortenerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateURL",
			Handler:    _Shortener_CreateURL_Handler,
		},
		{
			MethodName: "GetURL",
			Handler:    _Shortener_GetURL_Handler,
		},
		{
			MethodName: "GetStats",
			Handler:    _Shortener_GetStats_Handler,
		},
		{
			MethodName: "UpdateURL",
			Handler:    _Shortener_UpdateURL_Handler,
		},
		{
			MethodName: "DeleteURL",
			Handler:    _Shortener_DeleteURL_Handler,
		},
		{
			MethodName: "ListURLs",
			Handler:    _Shortener_ListURLs_Handler,
		},
		{
			MethodName: "GetQRCode",
			Handler:    _Shortener_GetQRCode_Handler,
		},
		{
			MethodName: "GetVisitSummary",
			Handler:    _Shortener_GetVisitSummary_Handler,
		},
		{
			MethodName: "GetVisitsByDate",
			Handler:    _Shortener_GetVisitsByDate_Handler,
		},
		{
			MethodName: "GetVisitsByField",
			Handler:    _Shortener_GetVisitsByField_Handler,
		},
		{
			MethodName: "GetRecentVisits",
			Handler:    _Shortener_GetRecentVisits_Handler,
		},
		{
			MethodName: "GetOrphanVisits",
			Handler:    _Shortener_GetOrphanVisits_Handler,
		},
		{
			MethodName: "ListTags",
			Handler:    _Shortener_ListTags_Handler,
		},
		{
			MethodName: "CreateTag",
			Handler:    _Shortener_CreateTag_Handler,
		},
		{
			MethodName: "RenameTag",
			Handler:    _Shortener_RenameTag_Handler,
		},
		{
			MethodName: "DeleteTag",
			Handler:    _Shortener_DeleteTag_Handler,
		},
		{
			MethodName: "GetTagStats",
			Handler:    _Shortener_GetTagStats_Handler,
		},
		{
			MethodName: "PreviewURL",
			Handler:    _Shortener_PreviewURL_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "url_service.proto",
}

const (
	Auth_Login_FullMethodName              = "/Auth/Login"
	Auth_OIDCAuthURL_FullMethodName        = "/Auth/OIDCAuthURL"
	Auth_OIDCCallback_FullMethodName       = "/Auth/OIDCCallback"
	Auth_ListOIDCProviders_FullMethodName  = "/Auth/ListOIDCProviders"
	Auth_CreateOIDCProvider_FullMethodName = "/Auth/CreateOIDCProvider"
	Auth_DeleteOIDCProvider_FullMethodName = "/Auth/DeleteOIDCProvider"
	Auth_CreateAPIKey_FullMethodName       = "/Auth/CreateAPIKey"
	Auth_ListAPIKeys_FullMethodName        = "/Auth/ListAPIKeys"
	Auth_RevokeAPIKey_FullMethodName       = "/Auth/RevokeAPIKey"
	Auth_RollAPIKey_FullMethodName         = "/Auth/RollAPIKey"
	Auth_GetCurrentUser_FullMethodName     = "/Auth/GetCurrentUser"
)

// AuthClient is the client API for Auth service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthClient interface {
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	OIDCAuthURL(ctx context.Context, in *OIDCAuthURLRequest, opts ...grpc.CallOption) (*OIDCAuthURLResponse, error)
	OIDCCallback(ctx context.Context, in *OIDCCallbackRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	ListOIDCProviders(ctx context.Context, in *ListOIDCProvidersRequest, opts ...grpc.CallOption) (*ListOIDCProvidersResponse, error)
	CreateOIDCProvider(ctx context.Context, in *CreateOIDCProviderRequest, opts ...grpc.CallOption) (*OIDCProvider, error)
	DeleteOIDCProvider(ctx context.Context, in *DeleteOIDCProviderRequest, opts ...grpc.CallOption) (*DeleteOIDCProviderResponse, error)
	CreateAPIKey(ctx context.Context, in *CreateAPIKeyRequest, opts ...grpc.CallOption) (*CreateAPIKeyResponse, error)
	ListAPIKeys(ctx context.Context, in *ListAPIKeysRequest, opts ...grpc.CallOption) (*ListAPIKeysResponse, error)
	RevokeAPIKey(ctx context.Context, in *RevokeAPIKeyRequest, opts ...grpc.CallOption) (*RevokeAPIKeyResponse, error)
	RollAPIKey(ctx context.Context, in *RollAPIKeyRequest, opts ...grpc.CallOption) (*CreateAPIKeyResponse, error)
	GetCurrentUser(ctx context.Context, in *GetCurrentUserRequest, opts ...grpc.CallOption) (*UserInfo, error)
}

type authClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthClient(cc grpc.ClientConnInterface) AuthClient {
	return &authClient{cc}
}

func (c *authClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, Auth_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) OIDCAuthURL(ctx context.Context, in *OIDCAuthURLRequest, opts ...grpc.CallOption) (*OIDCAuthURLResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OIDCAuthURLResponse)
	err := c.cc.Invoke(ctx, Auth_OIDCAuthURL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) OIDCCallback(ctx context.Context, in *OIDCCallbackRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, Auth_OIDCCallback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) ListOIDCProviders(ctx context.Context, in *ListOIDCProvidersRequest, opts ...grpc.CallOption) (*ListOIDCProvidersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListOIDCProvidersResponse)
	err := c.cc.Invoke(ctx, Auth_ListOIDCProviders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) CreateOIDCProvider(ctx context.Context, in *CreateOIDCProviderRequest, opts ...grpc.CallOption) (*OIDCProvider, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OIDCProvider)
	err := c.cc.Invoke(ctx, Auth_CreateOIDCProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) DeleteOIDCProvider(ctx context.Context, in *DeleteOIDCProviderRequest, opts ...grpc.CallOption) (*DeleteOIDCProviderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteOIDCProviderResponse)
	err := c.cc.Invoke(ctx, Auth_DeleteOIDCProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) CreateAPIKey(ctx context.Context, in *CreateAPIKeyRequest, opts ...grpc.CallOption) (*CreateAPIKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAPIKeyResponse)
	err := c.cc.Invoke(ctx, Auth_CreateAPIKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) ListAPIKeys(ctx context.Context, in *ListAPIKeysRequest, opts ...grpc.CallOption) (*ListAPIKeysResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAPIKeysResponse)
	err := c.cc.Invoke(ctx, Auth_ListAPIKeys_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) RevokeAPIKey(ctx context.Context, in *RevokeAPIKeyRequest, opts ...grpc.CallOption) (*RevokeAPIKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeAPIKeyResponse)
	err := c.cc.Invoke(ctx, Auth_RevokeAPIKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) RollAPIKey(ctx context.Context, in *RollAPIKeyRequest, opts ...grpc.CallOption) (*CreateAPIKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAPIKeyResponse)
	err := c.cc.Invoke(ctx, Auth_RollAPIKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) GetCurrentUser(ctx context.Context, in *GetCurrentUserRequest, opts ...grpc.CallOption) (*UserInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserInfo)
	err := c.cc.Invoke(ctx, Auth_GetCurrentUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServer is the server API for Auth service.
// All implementations must embed UnimplementedAuthServer
// for forward compatibility.
type AuthServer interface {
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	OIDCAuthURL(context.Context, *OIDCAuthURLRequest) (*OIDCAuthURLResponse, error)
	OIDCCallback(context.Context, *OIDCCallbackRequest) (*LoginResponse, error)
	ListOIDCProviders(context.Context, *ListOIDCProvidersRequest) (*ListOIDCProvidersResponse, error)
	CreateOIDCProvider(context.Context, *CreateOIDCProviderRequest) (*OIDCProvider, error)
	DeleteOIDCProvider(context.Context, *DeleteOIDCProviderRequest) (*DeleteOIDCProviderResponse, error)
	CreateAPIKey(context.Context, *CreateAPIKeyRequest) (*CreateAPIKeyResponse, error)
	ListAPIKeys(context.Context, *ListAPIKeysRequest) (*ListAPIKeysResponse, error)
	RevokeAPIKey(context.Context, *RevokeAPIKeyRequest) (*RevokeAPIKeyResponse, error)
	RollAPIKey(context.Context, *RollAPIKeyRequest) (*CreateAPIKeyResponse, error)
	GetCurrentUser(context.Context, *GetCurrentUserRequest) (*UserInfo, error)
	mustEmbedUnimplementedAuthServer()
}

// UnimplementedAuthServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthServer struct{}

func (UnimplementedAuthServer) Login(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedAuthServer) OIDCAuthURL(context.Context, *OIDCAuthURLRequest) (*OIDCAuthURLResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OIDCAuthURL not implemented")
}
func (UnimplementedAuthServer) OIDCCallback(context.Context, *OIDCCallbackRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OIDCCallback not implemented")
}
func (UnimplementedAuthServer) ListOIDCProviders(context.Context, *ListOIDCProvidersRequest) (*ListOIDCProvidersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListOIDCProviders not implemented")
}
func (UnimplementedAuthServer) CreateOIDCProvider(context.Context, *CreateOIDCProviderRequest) (*OIDCProvider, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOIDCProvider not implemented")
}
func (UnimplementedAuthServer) DeleteOIDCProvider(context.Context, *DeleteOIDCProviderRequest) (*DeleteOIDCProviderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteOIDCProvider not implemented")
}
func (UnimplementedAuthServer) CreateAPIKey(context.Context, *CreateAPIKeyRequest) (*CreateAPIKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAPIKey not implemented")
}
func (UnimplementedAuthServer) ListAPIKeys(context.Context, *ListAPIKeysRequest) (*ListAPIKeysResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAPIKeys not implemented")
}
func (UnimplementedAuthServer) RevokeAPIKey(context.Context, *RevokeAPIKeyRequest) (*RevokeAPIKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevokeAPIKey not implemented")
}
func (UnimplementedAuthServer) RollAPIKey(context.Context, *RollAPIKeyRequest) (*CreateAPIKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RollAPIKey not implemented")
}
func (UnimplementedAuthServer) GetCurrentUser(context.Context, *GetCurrentUserRequest) (*UserInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCurrentUser not implemented")
}
func (UnimplementedAuthServer) mustEmbedUnimplementedAuthServer() {}
func (UnimplementedAuthServer) testEmbeddedByValue()              {}

// UnsafeAuthServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthServer will
// result in compilation errors.
type UnsafeAuthServer interface {
	mustEmbedUnimplementedAuthServer()
}

func RegisterAuthServer(s grpc.ServiceRegistrar, srv AuthServer) {
	// If the following call pancis, it indicates UnimplementedAuthServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Auth_ServiceDesc, srv)
}

func _Auth_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Auth_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_OIDCAuthURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OIDCAuthURLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).OIDCAuthURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Auth_OIDCAuthURL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).OIDCAuthURL(ctx, req.(*OIDCAuthURLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_OIDCCallback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OIDCCallbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).OIDCCallback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Auth_OIDCCallback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).OIDCCallback(ctx, req.(*OIDCCallbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_ListOIDCProviders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOIDCProvidersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).ListOIDCProviders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Auth_ListOIDCProviders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).ListOIDCProviders(ctx, req.(*ListOIDCProvidersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_CreateOIDCProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOIDCProviderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).CreateOIDCProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Auth_CreateOIDCProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).CreateOIDCProvider(ctx, req.(*CreateOIDCProviderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_DeleteOIDCProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteOIDCProviderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).DeleteOIDCProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Auth_DeleteOIDCProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).DeleteOIDCProvider(ctx, req.(*DeleteOIDCProviderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_CreateAPIKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAPIKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).CreateAPIKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Auth_CreateAPIKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).CreateAPIKey(ctx, req.(*CreateAPIKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_ListAPIKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAPIKeysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).ListAPIKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Auth_ListAPIKeys_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).ListAPIKeys(ctx, req.(*ListAPIKeysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_RevokeAPIKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeAPIKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).RevokeAPIKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Auth_RevokeAPIKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).RevokeAPIKey(ctx, req.(*RevokeAPIKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_RollAPIKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RollAPIKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).RollAPIKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Auth_RollAPIKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).RollAPIKey(ctx, req.(*RollAPIKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_GetCurrentUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCurrentUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).GetCurrentUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Auth_GetCurrentUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).GetCurrentUser(ctx, req.(*GetCurrentUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Auth_ServiceDesc is the grpc.ServiceDesc for Auth service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Auth_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Auth",
	HandlerType: (*AuthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _Auth_Login_Handler,
		},
		{
			MethodName: "OIDCAuthURL",
			Handler:    _Auth_OIDCAuthURL_Handler,
		},
		{
			MethodName: "OIDCCallback",
			Handler:    _Auth_OIDCCallback_Handler,
		},
		{
			MethodName: "ListOIDCProviders",
			Handler:    _Auth_ListOIDCProviders_Handler,
		},
		{
			MethodName: "CreateOIDCProvider",
			Handler:    _Auth_CreateOIDCProvider_Handler,
		},
		{
			MethodName: "DeleteOIDCProvider",
			Handler:    _Auth_DeleteOIDCProvider_Handler,
		},
		{
			MethodName: "CreateAPIKey",
			Handler:    _Auth_CreateAPIKey_Handler,
		},
		{
			MethodName: "ListAPIKeys",
			Handler:    _Auth_ListAPIKeys_Handler,
		},
		{
			MethodName: "RevokeAPIKey",
			Handler:    _Auth_RevokeAPIKey_Handler,
		},
		{
			MethodName: "RollAPIKey",
			Handler:    _Auth_RollAPIKey_Handler,
		},
		{
			MethodName: "GetCurrentUser",
			Handler:    _Auth_GetCurrentUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "url_service.proto",
}
