version: "3.4"
services: 
    grpcbackend:
        hostname: grpcbackend
        build: backend/.
        depends_on: 
            - redis

    redis:
        image: "redis:alpine"
        privileged: true
        command: >
            sh -c "echo never > /sys/kernel/mm/transparent_hugepage/enabled &&
            echo never > /sys/kernel/mm/transparent_hugepage/defrag &&
            redis-server --requirepass mysecretpassword"
        sysctls:
            - net.core.somaxconn=1024


        
    frontend:
        hostname: frontend
        build: frontend-go/.
        dns_search: .
        ports:
            - 8081:8081
        depends_on: 
            - grpcbackend