FROM golang:1.25-alpine AS builder

RUN apk add --no-cache git

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -o grpc-server .

FROM alpine:3.21

RUN apk add --no-cache ca-certificates

WORKDIR /app

COPY --from=builder /app/grpc-server .
COPY --from=builder /app/migrations/ ./migrations/
COPY --from=builder /app/pb/url_service.swagger.json ./pb/
COPY --from=builder /app/config.json .

EXPOSE 9000 8080

CMD ["./grpc-server"]
