DROP TABLE IF EXISTS sessions;
DROP TABLE IF EXISTS oidc_providers;
DROP INDEX IF EXISTS idx_users_oidc;
ALTER TABLE api_keys DROP COLUMN IF EXISTS scopes;
ALTER TABLE users DROP COLUMN IF EXISTS is_active;
ALTER TABLE users DROP COLUMN IF EXISTS oidc_issuer;
ALTER TABLE users DROP COLUMN IF EXISTS oidc_subject;
ALTER TABLE users DROP COLUMN IF EXISTS role;
ALTER TABLE users DROP COLUMN IF EXISTS password_hash;
