DROP TABLE IF EXISTS domains;
DROP INDEX IF EXISTS idx_urls_domain;
ALTER TABLE urls DROP COLUMN IF EXISTS domain;
ALTER TABLE urls DROP COLUMN IF EXISTS is_crawlable;
ALTER TABLE urls DROP COLUMN IF EXISTS redirect_type;
ALTER TABLE urls DROP COLUMN IF EXISTS max_visits;
ALTER TABLE urls DROP COLUMN IF EXISTS title;
ALTER TABLE urls ALTER COLUMN code TYPE VARCHAR(10);
