DROP TABLE IF EXISTS sign_in_events;
ALTER TABLE sessions DROP COLUMN IF EXISTS revoked;
ALTER TABLE sessions DROP COLUMN IF EXISTS label;
ALTER TABLE sessions DROP COLUMN IF EXISTS user_agent;
ALTER TABLE users DROP COLUMN IF EXISTS theme;
