//
//GetURL will take in a long url, generate a 6 character code to associate with the URL
//and store it in a redis datastore for XX amount of time. (length of time undetermined)

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0-devel
// 	protoc        v3.11.4
// source: protos/url_service.proto

package url_service

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ShortURLReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LongUrl string `protobuf:"bytes,1,opt,name=long_url,json=longUrl,proto3" json:"long_url,omitempty"`
}

func (x *ShortURLReq) Reset() {
	*x = ShortURLReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_url_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShortURLReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortURLReq) ProtoMessage() {}

func (x *ShortURLReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_url_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortURLReq.ProtoReflect.Descriptor instead.
func (*ShortURLReq) Descriptor() ([]byte, []int) {
	return file_protos_url_service_proto_rawDescGZIP(), []int{0}
}

func (x *ShortURLReq) GetLongUrl() string {
	if x != nil {
		return x.LongUrl
	}
	return ""
}

type ShortURLResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShortUrl string `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
}

func (x *ShortURLResp) Reset() {
	*x = ShortURLResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_url_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShortURLResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortURLResp) ProtoMessage() {}

func (x *ShortURLResp) ProtoReflect() protoreflect.Message {
	mi := &file_protos_url_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortURLResp.ProtoReflect.Descriptor instead.
func (*ShortURLResp) Descriptor() ([]byte, []int) {
	return file_protos_url_service_proto_rawDescGZIP(), []int{1}
}

func (x *ShortURLResp) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

var File_protos_url_service_proto protoreflect.FileDescriptor

var file_protos_url_service_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x75, 0x72, 0x6c, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x28, 0x0a, 0x0b, 0x53, 0x68,
	0x6f, 0x72, 0x74, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x71, 0x12, 0x19, 0x0a, 0x08, 0x6c, 0x6f, 0x6e,
	0x67, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6c, 0x6f, 0x6e,
	0x67, 0x55, 0x72, 0x6c, 0x22, 0x2b, 0x0a, 0x0c, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x52, 0x4c,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x5f, 0x75, 0x72,
	0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x72,
	0x6c, 0x32, 0x35, 0x0a, 0x09, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x12, 0x28,
	0x0a, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x52, 0x4c, 0x12, 0x0c, 0x2e, 0x53, 0x68,
	0x6f, 0x72, 0x74, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x71, 0x1a, 0x0d, 0x2e, 0x53, 0x68, 0x6f, 0x72,
	0x74, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x73, 0x70, 0x42, 0x0f, 0x5a, 0x0d, 0x2e, 0x3b, 0x75, 0x72,
	0x6c, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_protos_url_service_proto_rawDescOnce sync.Once
	file_protos_url_service_proto_rawDescData = file_protos_url_service_proto_rawDesc
)

func file_protos_url_service_proto_rawDescGZIP() []byte {
	file_protos_url_service_proto_rawDescOnce.Do(func() {
		file_protos_url_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_url_service_proto_rawDescData)
	})
	return file_protos_url_service_proto_rawDescData
}

var file_protos_url_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protos_url_service_proto_goTypes = []interface{}{
	(*ShortURLReq)(nil),  // 0: ShortURLReq
	(*ShortURLResp)(nil), // 1: ShortURLResp
}
var file_protos_url_service_proto_depIdxs = []int32{
	0, // 0: Shortener.CreateURL:input_type -> ShortURLReq
	1, // 1: Shortener.CreateURL:output_type -> ShortURLResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_url_service_proto_init() }
func file_protos_url_service_proto_init() {
	if File_protos_url_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_url_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShortURLReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_url_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShortURLResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_url_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_url_service_proto_goTypes,
		DependencyIndexes: file_protos_url_service_proto_depIdxs,
		MessageInfos:      file_protos_url_service_proto_msgTypes,
	}.Build()
	File_protos_url_service_proto = out.File
	file_protos_url_service_proto_rawDesc = nil
	file_protos_url_service_proto_goTypes = nil
	file_protos_url_service_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ShortenerClient is the client API for Shortener service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ShortenerClient interface {
	CreateURL(ctx context.Context, in *ShortURLReq, opts ...grpc.CallOption) (*ShortURLResp, error)
}

type shortenerClient struct {
	cc grpc.ClientConnInterface
}

func NewShortenerClient(cc grpc.ClientConnInterface) ShortenerClient {
	return &shortenerClient{cc}
}

func (c *shortenerClient) CreateURL(ctx context.Context, in *ShortURLReq, opts ...grpc.CallOption) (*ShortURLResp, error) {
	out := new(ShortURLResp)
	err := c.cc.Invoke(ctx, "/Shortener/CreateURL", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShortenerServer is the server API for Shortener service.
type ShortenerServer interface {
	CreateURL(context.Context, *ShortURLReq) (*ShortURLResp, error)
}

// UnimplementedShortenerServer can be embedded to have forward compatible implementations.
type UnimplementedShortenerServer struct {
}

func (*UnimplementedShortenerServer) CreateURL(context.Context, *ShortURLReq) (*ShortURLResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateURL not implemented")
}

func RegisterShortenerServer(s *grpc.Server, srv ShortenerServer) {
	s.RegisterService(&_Shortener_serviceDesc, srv)
}

func _Shortener_CreateURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShortURLReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShortenerServer).CreateURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Shortener/CreateURL",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShortenerServer).CreateURL(ctx, req.(*ShortURLReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Shortener_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Shortener",
	HandlerType: (*ShortenerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateURL",
			Handler:    _Shortener_CreateURL_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/url_service.proto",
}
